server:
  port: 8530
#  port: 8443
#  ssl:
#    key-store: classpath:mykeys.jks
#    key-store-password: liuyufei
#    key-password: liuyufei
##  error:
##    whitelabel:
##      enabled: false
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
    content-type: text/html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/score?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
#    url: jdbc:mysql://10.64.8.178:3306/score?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: root12345678 #    password: Admin1234?! hikari: maximum-pool-size: 10 连接池最大连接数 minimum-idle: 0 允许的最小空闲属
      idle-timeout: 180000 #空闲超时是 180000 毫秒，当数据库连接的空闲时间大于180000毫秒时，这些空闲超时的连接会被关闭，直到超时的空闲连接数达到 minimum-idle的值
      connection-test-query: select 1 # 测试连接是否可用的query 语句 在oracle是 select 1 from dualuuu
  jpa:
    database: mysql
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
#  mvc:
#    throw-exception-if-no-handler-found: true
#    resources:
#      add-mappings: false
management:
  port: 9001
  security:
    enabled: false