server:
  port: 8530
#  port: 8443
#  ssl:
#    key-store: classpath:mykeys.jks
#    key-store-password: liuyufei
#    key-password: liuyufei
##  error:
##    whitelabel:
##      enabled: false
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
    content-type: text/html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/score?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
#    password: root,123456
    password: 123456
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
#  mvc:
#    throw-exception-if-no-handler-found: true
#    resources:
#      add-mappings: false
management:
  port: 9001
  security:
    enabled: false